services:
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:latest
    shm_size: 128mb
    restart: always
    ports:
      - "5432:5432"
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: password
       POSTGRES_DB: incident_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    container_name: redis_layer 
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    environment:
      - REDIS_ARGS=--requirepass password --appendonly yes
    restart: unless-stopped
  
  agent:
    image: inc-agent:latest
    container_name: inc-agent
    ports:
      - 8001:8001
    restart: always 
  
  api:
    image: inc-agent-api:latest
    container_name: inc-agent-api
    ports:
      - 8000:8000
    restart: always
  
  consumer:
    image: inc-agent-consumer:latest
    container_name: consumer
    restart: always

volumes:
  postgres_data:
  redis_data:

