apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: opsagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      serviceAccountName: agent-service-account
      containers: 
        - image: jaganath1508/ops-agent:latest
          name:  agent
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: opsagent-config
            - secretRef:
                name: opsagent-secret
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: opsagent
spec:
  selector:
    app: agent
  type: ClusterIP
  ports:
    - port:  8001
      targetPort:  8001