kind: apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: opsagent
  labels:  
spec:
  selector:
    matchLabels:
      app: agent
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: agent 
    spec:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name:  name
      restartPolicy: Always
      containers:
      - name:  
        image:  jaganath1508/ops-agent:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  8001
