apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-api
  namespace: opsagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: jaganath1508/ops-agent-consumer
        envFrom:
          - configMapRef:
              name: opsagent-config
          - secretRef:
              name: opsagent-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"

