apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: opsagent
data:
  KAFKA_LISTENERS: "CONTROLLER://localhost:9091,CLIENT://0.0.0.0:9092,EXTERNAL://0.0.0.0:30092"
  KAFKA_ADVERTISED_LISTENERS: "CLIENT://kafka-service:9092,EXTERNAL://192.168.49.2:30092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT "
  KAFKA_NODE_ID: "1"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9091"
  KAFKA_INTER_BROKER_LISTENER_NAME: "CLIENT"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"


