apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: opsagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:latest
        name:  redis
        command: ["redis-server"]
        args: ["--requirepass", "password", "--appendonly", "yes"]
        ports:
          - containerPort: 6379
            name: redis
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: opsagent
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis

